name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Publish
        uses: softprops/action-gh-release@v1
        with:
          body: '[More see Changelog](https://github.com/sns-sdks/go-twitter/blob/master/CHANGELOG.md)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
